### ISSUE TITLE
Can't expand array in console

### ISSUE THREAD

**Issue by jazzdan** [replayio/node#29]
Recording of behavior: https://app.replay.io/recording/9bf051a9-6666-4d9f-bddf-91874bf6bc5a

Original recording: https://app.replay.io/recording/61ef8700-4d92-4257-8f4e-2ec39d6270f4

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-10](https://linear.app/replay/issue/RUN-10/cant-expand-array-in-console)
