### ISSUE TITLE
Support miniflare

### ISSUE THREAD

**Issue by jasonLaster** [replayio/node#39]
Miniflare is a local-development environment build for Cloudflare Workers.

It is written in Typescript and should _just work_

**Worker.js**
```js
addEventListener("fetch", (event) => {
  event.respondWith(new Response("Hello Miniflare :)"));
});
```

**CLI**
```bash
replay-node node_modules/.bin/miniflare worker.js
```

https://blog.cloudflare.com/miniflare/
https://miniflare.dev/get-started/cli

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-311](https://linear.app/replay/issue/RUN-311/support-miniflare)
