### ISSUE TITLE
Environment variable redaction

### ISSUE THREAD

**Issue by bhackett1024** [replayio/node#55]
It would be good to redact environment variables from recordings by default --- when making a node recording users will not expect it to expose all of their potentially sensitive environment variables to people viewing the recording.  I think the ideal behavior here is that the contents of environment variables which are never explicitly accessed by the script should be redacted.  With node that is a bit tricky because there is a `process.env` object that contains all environment variables, and which is normally accessed like `process.env.FOO` but requires the VM to load the contents of all environment variables into its state.  The environment is also frequently used in spread operators when spawning subprocesses with different environment settings.  So this is non-trivial to get right, and whatever we do should be reusable more generally for redaction.

Near term, we should make sure we have good messaging around the fact that node recordings have information about the environment variables that are available.  Filed https://github.com/RecordReplay/devtools/issues/6064 and https://github.com/RecordReplay/devtools/issues/6065 for this.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-314](https://linear.app/replay/issue/RUN-314/environment-variable-redaction)
