### ISSUE TITLE
Unimplemented callback napi_add_finalizer

### ISSUE THREAD

**Issue by hbenl** [replayio/node#69]
When I try to record the [napi.js](https://github.com/RecordReplay/devtools/blob/master/test/examples/node/napi.js) example for e2e tests it prints out "Unimplemented callback napi_add_finalizer" several times and marks the recording as unusable.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-315](https://linear.app/replay/issue/RUN-315/unimplemented-callback-napi-add-finalizer)
