### ISSUE TITLE
Node sourcemaps are not being applied

### ISSUE THREAD

**Issue by hbenl** [replayio/node#83]
### What steps will reproduce the bug?

Create a recording with node of a script with sourcemaps and open the recording in Replay.

### What do you see instead?

Sourcemaps are not being applied.

### Additional information

The `source` objects we get from basic processing in node recordings don't contain a `sourceMapURL`, but the sourcemaps are uploaded with their `sourceMapURL`, so the backend thinks they don't match.
We could:
1. ensure that the `source` objects from basic processing do contain their `sourceMapURL`
2. write the sourcemaps in node recordings without their `sourceMapURL`
3. ignore the `sourceMapURL` when matching sourcemaps in the backend if it is `undefined` in the `source` object from basic processing

The first option seems to be the most desirable, but I don't know how much effort that would be. Alternatively the third option would be easy to do and should be safe if we require the source's `contentHash` to be available and match in that case.

**Comment by hbenl** [comment]
@bhackett1024 which option do you prefer?

**Comment by gideonred** [comment]
Putting in Todo this sprint for Holger to have a look.

**Comment by hbenl** [comment]
I tried to implement this similar to how it works in gecko-dev: save the `sourceMapURL`s in a Map and read from that Map in `Target_getSourceMapURL()`. However, this doesn't work, I guess that the `Debugger.scriptParsed` event (from which we get the `sourceMapURL`) is sent *after* the `Target.getSourceMapURL` command is sent from `recordreplay::OnNewSource()`. And `Target_getSourceMapURL()` is synchronous, so we can't wait for the `sourceMapURL` to show up.
@loganfsmyth What do you think about option 3? If a source's url and content match I think it's safe to apply the sourcemap.

**Comment by bhackett1024** [comment]
> @bhackett1024 That seems to work, but would it break anything?

I don't think this would break anything, this sounds like a good solution.  Eventually it would be best to consolidate the scriptParsed and RegisterScript logic and if we're doing them in similar places that would be a good step forwards and makes more sense anyways.
